### ISSUE TITLE
While running on windows machine, it doesn't get redirected to the API project

### ISSUE THREAD

**Issue by rahulsahay19** [NileshGule/AKS-learning-series#5]
Hi,

While running on windows, I am changing the port number to 

http://localhost:8081/api/techtalks/ for api_url.

But, after docker compose up, redirection doesn't happen. Anything, wrong I am doing here? Or for windows, do i need to change the strategy for hosting url.

Thanks,
Rahul

**Comment by NileshGule** [comment]
hi @rahulsahay19 
Thanks for raising the issue. The problem is due to the way Docker compose works internally. It creates an internal network and we need to use the service discovery using the name of the service instead of the localhost.
I have checked in recent changes to make it work with 8081 port. I had to also add the statement in the Dockerfile to allow URLs to access 8081 port 
**ENV ASPNETCORE_URLS http://+:8081** 

Specifically for windows, we also need to use the IP address of the machine while populating the data in the SQL container as mentioned in issue #3

In the TechTalksController class as well I had to hardcode the URL as it was not picking up the dynamic path provided via environment variable as **API_BASE_URL = "http://techtalks.api:8081/api/techtalks";**

With these changes, I managed to get it working. 

Hope this helps. Let me know if you are still facing some issues.

You can refer to following commits for the fixes
- 61e010a5cf361f9795f116a2de60559f7422f3e6
- a0c82d9384f382262bd87c4bafb0c0d27352f6f3
- bfdd8b9d091892980403e9337e98766cd98ec66b

Note: I will be reverting these code changes in order for the code to work with Kubernetes in future. This fix is only to make the code work with docker-compose on Windows.

<img width="1163" alt="8081 port changes" src="https://user-images.githubusercontent.com/1298374/61312512-2471ab00-a82b-11e9-958f-a51d5db341ab.PNG">
<img width="1059" alt="Unable to redirect API call" src="https://user-images.githubusercontent.com/1298374/61312514-2471ab00-a82b-11e9-9be5-13cbb2b3e63b.PNG">
