### ISSUE TITLE
'microsoft/mssql-server-linux:2017-latest' container have a connection issue with another container.

### ISSUE THREAD

**Issue by tutul2010** [NileshGule/AKS-learning-series#8]
https://docs.microsoft.com/en-us/answers/questions/191498/how-to-pass-sql-db-container-connection-string-to.html

**Comment by NileshGule** [comment]
@tutul2010 you need to use the name of the SQL service specified in the docker compose file while connecting from the API and not localhost

You can see example of this here
techtalks.api:
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=sql.data,1433;Initial Catalog=TechTalksDB;User Id=SA;Password=June2018;MultipleActiveResultSets=True;
    depends_on: 
      - sql.data
In order to populate the data, I use the initialize database script using Azure Data studio and connect to the SQL Server 2017. Make sure to run the docker compose up command to get the SQL Server 2017 up and running

![image](https://user-images.githubusercontent.com/1298374/105861092-4e637a80-6029-11eb-985f-ab7d3286986e.png)

Here is the output shown in the UI where data is pulled from the WebAPI
![image](https://user-images.githubusercontent.com/1298374/105861406-a4382280-6029-11eb-81b6-f54649fe7768.png)

**Comment by tutul2010** [comment]
Thanks!!! Thanks for the update. i will try and update u.
